bin.includes = META-INF/,\
               mariadb-java-client-3.5.7.jar,\
               infinispan-commons-16.0.5.jar,\
               infinispan-core-16.0.5.jar,\
               jakarta.annotation-api-2.1.1.jar,\
               jakarta.persistence-api-3.1.0.jar,\
               wildfly-clustering-server-api-39.0.1.Final.jar,\
               wildfly-clustering-server-api-9.0.2.Final.jar,\
               wildfly-elytron-client-2.8.2.Final.jar,\
               hibernate-core-6.6.40.Final.jar,\
               jakarta.enterprise.concurrent-api-3.0.3.jar,\
               jakarta.interceptor-api-2.1.0.jar,\
               jboss-ejb3-ext-api-2.4.0.Final.jar,\
               byte-buddy-1.17.5.jar
